version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"name\":\"public\", \"variables\":[]}]"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  frontend:
    image: lblod/frontend-poc-future-loket-hoofdloket:feature-ipdc-integration
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  database:
    image: semtech/sparql-parser:latest
    volumes:
      - ./config/authorization:/config
      - ./data/authorization:/data
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_TIMEOUT: 300
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  login:
    image: lblod/acmidm-login-service:0.12.0
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op/"
      MU_APPLICATION_AUTH_CLIENT_ID: "97b992e0-dcd6-41c2-8c3d-b6498b42d159"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://future-loket-main.lblod.info/authorization/callback"
      DEBUG_LOG_TOKENSETS: "true"
    volumes:
      - ./config/openid:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.2
    links:
    - resource:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:1.24.0
    environment:
      CACHE_CLEAR_PATH: "http://resourcecache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  ipdc-ldes-consumer:
    image: redpencil/ldes-consumer:feature-use-streaming-backpressure
    environment:
      LDES_STREAM: "https://future-loket.lblod.info/ipdc-instance-feed"
      LDES_ENDPOINT_VIEW: "https://ipdc.tni-vlaanderen.be/doc/instantiesnapshot?pageNumber=0"
      CRON_PATTERN: "*/10 * * * * *" # run the job every 10 seconds
      LDES_POLLING_INTERVAL: 30000 # every 30 seconds
      LDES_LOGGING_LEVEL: "debug"
      REPLACE_VERSIONS: "false"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/ipdc/ldes-data"
      PERSIST_STATE: "true"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  ldes-object:
    image: lblod/ldes-make-object-service:feature-deep-copy-blank-nodes
    environment:
      LANDING_ZONE_GRAPH: "http://mu.semte.ch/graphs/ipdc/ldes-data"
      TARGET_GRAPH: "http://mu.semte.ch/graphs/public"
      DEEP_COPY_BLANK_NODES: "true"
      MAX_BODY_SIZE: "10mb"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  uuid-generation:
    image: redpencil/uuid-generation:0.3.0
    volumes:
      - ./config/uuid-generation/:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
