version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      SESSION_COOKIE_SECURE: "on"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
  database:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  login:
    image: lblod/acmidm-login-service:0.12.0
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op/"
      MU_APPLICATION_AUTH_CLIENT_ID: "97b992e0-dcd6-41c2-8c3d-b6498b42d159"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://future-loket-main.lblod.info/authorization/callback"
      DEBUG_LOG_TOKENSETS: "true"
    volumes:
      - ./config/openid:/config
  resource:
    image: semtech/mu-cl-resources:1.23.0
    volumes:
      - ./config/resources:/config
