version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"name\":\"public\", \"variables\":[]}]"
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
  database:
    image: semtech/sparql-parser:latest
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:feature-deltas-with-only-effective-changes
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_TIMEOUT: 300
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
  login:
    image: lblod/acmidm-login-service:0.12.0
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op/"
      MU_APPLICATION_AUTH_CLIENT_ID: "97b992e0-dcd6-41c2-8c3d-b6498b42d159"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://future-loket-main.lblod.info/authorization/callback"
      DEBUG_LOG_TOKENSETS: "true"
    volumes:
      - ./config/openid:/config
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:1.23.0
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
  ipdc-ldes-consumer:
    image: redpencil/ldes-consumer:feature-use-streaming-backpressure
    environment:
      LDES_STREAM: "https://future-loket.lblod.info/ipdc-instance-feed"
      LDES_ENDPOINT_VIEW: "https://ipdc.tni-vlaanderen.be/doc/instantiesnapshot?pageNumber=0"
      CRON_PATTERN: "*/10 * * * * *" # run the job every 10 seconds
      LDES_POLLING_INTERVAL: 30000 # every 30 seconds
      SAVE_ALL_VERSIONS_IGNORING_TIMESTAMP_DATA: "true"
      REPLACE_VERSIONS: "false"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/ipdc/ldes-data"
      PERSIST_STATE: "true"
    labels:
      - "logging=true"
  ldes-object:
    image: lblod/ldes-make-object-service
    environment:
      LANDING_ZONE_GRAPH: "http://mu.semte.ch/graphs/ipdc/ldes-data"
      TARGET_GRAPH: "http://mu.semte.ch/graphs/public"
    labels:
      - "logging=true"
