(define-resource user ()
  :class (s-prefix "foaf:Person")
  :resource-base (s-url "http://data.lblod.info/id/gebruiker/")
  :properties `((:voornaam :string ,(s-prefix "foaf:firstName"))
                 (:achternaam :string ,(s-prefix "foaf:familyName")))
  :has-many `((account :via ,(s-prefix "foaf:account")
                :as "account")
               (administrative-unit :via ,(s-prefix "foaf:member")
                 :as "administrative-units"))
  :on-path "users")

(define-resource account ()
  :class (s-prefix "foaf:OnlineAccount")
  :resource-base (s-url "http://data.lblod.info/id/account/")
  :properties `((:provider :via ,(s-prefix "foaf:accountServiceHomepage"))
                 (:roles :string-set ,(s-prefix "ext:sessionRole"))
                 (:vo-id :via ,(s-prefix "dct:identifier")))
  :has-one `((user :via ,(s-prefix "foaf:account")
               :inverse t
               :as "user"))
  :on-path "accounts")

(define-resource administrative-unit ()
  :class (s-prefix "besluit:Bestuurseenheid")
  :resource-base (s-url "http://data.lblod.info/id/bestuurseenheden/")
  :properties `((:naam :string ,(s-prefix "skos:prefLabel"))
                (:alternatieve-naam :string-set ,(s-prefix "skos:altLabel")))
  :has-one `((bestuurseenheid-classificatie-code :via ,(s-prefix "org:classification")
               :as "classificatie"))
  :features '(include-uri)
  :on-path "administrative-units")

(define-resource bestuurseenheid-classificatie-code ()
  :class (s-prefix "lblodOrg:BestuurseenheidClassificatieCode")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:scope-note :string ,(s-prefix "skos:scopeNote")))
  :resource-base (s-url "http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/")
  :features '(include-uri)
  :on-path "bestuurseenheid-classificatie-codes")
